### ISSUE TITLE
AutoPiIrrigator issue

### ISSUE THREAD

**Issue by yuanming59** [johri002/AutoPiIrrigator#9]
Dear Sir Johri : I am very interested in you have published " AutoPiIrrigator " in GitHub,
After study your AutoPiIrrigator project ,
There have three questions should clarify.
  1. What is the conponent model in the picture?Relay?SLA-5VDC-SL-C?
  2. What is the humidity sensor model BMP820 or BME820?
  3. I want know how to connect the temperature and humidity sensor?
Would you like to provide a whole hardware circuit diagram for me? 
   I would  like to copy your success experience. 
Please Take time to help me reply. Thanks for your  kindlness very much!
![BMP820 or BME820](https://user-images.githubusercontent.com/53809289/62921016-08d1d400-bdda-11e9-9c39-a275adfd05ba.jpg)
![what is the relay model in this picture](https://user-images.githubusercontent.com/53809289/62921017-096a6a80-bdda-11e9-98da-d487dfcff128.png)

**Comment by johri-lab** [comment]
> Dear Sir Johri : I am very interested in you have published " AutoPiIrrigator " in GitHub,
> After study your AutoPiIrrigator project ,
> There have three questions should clarify.
> 
> 1. What is the conponent model in the picture?Relay?SLA-5VDC-SL-C?
> 2. What is the humidity sensor model BMP820 or BME820?
> 3. I want know how to connect the temperature and humidity sensor?
>    Would you like to provide a whole hardware circuit diagram for me?
>    I would  like to copy your success experience.
>    Please Take time to help me reply. Thanks for your  kindlness very much!
>    ![BMP820 or BME820](https://user-images.githubusercontent.com/53809289/62921016-08d1d400-bdda-11e9-9c39-a275adfd05ba.jpg)
>    ![what is the relay model in this picture](https://user-images.githubusercontent.com/53809289/62921017-096a6a80-bdda-11e9-98da-d487dfcff128.png)

Use BME280 sensor and relay is selected according to the specification of the water pump motor it is connected to.
